# FUNDING.yml
# Configuration for funding information on GitHub repositories

github: # Replace with GitHub Sponsors-enabled usernames, e.g., ['LikhonScripts', 'ton_blockchain']
ko_fi: TONCoda # Replace with Ko-fi username, if 
buymeacoffee: likhonscriptsReplace with custom sponsorship URLs

# Note: Replace the placeholders with actual usernames or URLs specific to TONCoda
